# Generated by Django 4.2.7 on 2023-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_professional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gread_point_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='out_of_greadPoint',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
