# Generated by Django 4.2.7 on 2023-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_professional_traning'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_traning',
            name='course_institute_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
