# Generated by Django 4.2.7 on 2023-11-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EDepartment',
                'verbose_name_plural': 'EDepartments',
            },
        ),
        migrations.CreateModel(
            name='TEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('gread_point', models.FloatField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('course_end_date', models.DateField(blank=True, null=True)),
                ('department_descriptions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.edegree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.edepartment')),
            ],
            options={
                'verbose_name_plural': 'TEducations',
            },
        ),
    ]
