# Generated by Django 4.2.7 on 2023-11-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_edepartment_teducation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EDegree',
            new_name='Degree',
        ),
        migrations.RenameModel(
            old_name='EDepartment',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='TEducation',
            new_name='Education',
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Degree', 'verbose_name_plural': 'Degrees'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Educations'},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='degrees',
        ),
    ]
