# Generated by Django 4.2.7 on 2023-11-20 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_aboutme_created_at_aboutme_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='Birthday',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
