# Generated by Django 4.2.7 on 2023-11-24 15:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_education_gread_point_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_experience',
            name='work_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
