# Generated by Django 4.2.7 on 2026-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_professional_traning_course_institute_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_experience',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
